const AppState = {
    allPositions: [],
    allTags: [],
    currentTagFilter: null,
    quizTagFilters: [],
    quizQueue: [],
    quizCurrent: null,
    quizCorrect: 0,
    quizTotal: 0,
    currentDetailId: null,
    currentDetailFen: null,
    sfWorker: null,
    boardFlipped: false,
    detailFlipped: false,
    boardFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    lastTags: '',
    allGames: [],
    gameTagFilter: null,
    gameCollectionFilter: null,
    gameSearch: '',
    allCollections: [],
    currentGame: null,
    currentPly: 0,
    engineOn: false,
    engineEval: null,
    playMode: false,
    playBoardId: null,
    playStartFen: null,
    playChess: null,
    soundMuted: false,
    batchMode: false,
    batchCollectionId: null,
    batchCollectionName: null,
    batchGameIds: [],
    batchIndex: 0,
    searchFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    selectedGameIds: new Set(),
};

window.AppState = AppState;
